llm:
  claude:
    api_key: ${CLAUDE_API_KEY}
    base_url: ${CLAUDE_BASE_URL:-https://api.anthropic.com/v1}
    timeout_seconds: ${CLAUDE_TIMEOUT_SECONDS:-30}
    model: ${CLAUDE_MODEL:-claude-3-sonnet-20240229}