# Common:
base_dir: /home/galt/code/ai_chef
go_module_name: github.com/tfiling/ai-chef
additional_feedback: |

# crud_api_controller params:
entity_name: User
model: |
  type User struct {
      ID   string `json:"id" bson:"_id"`
      Username string `json:"name" validate:"required"`
  }

# feature_implementation.py
feature_description: |
  a component that uses Claude's API for generating recipes. There should be a Claude client component and a component that composes the prompts for generating the recipes using Claude's client component.
